services:
  - type: web
    name: smart-summary-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: backend
    plan: free
    region: oregon
